Repository Venture-Miner/wagademy, pull requests merged in 2024-04, with the labels that each got.

#68 4.0 - List jobs, create job, update job and delete job (frontend)
  apps/frontend/src/app/pages/company/hiring/hiring.component.html
  apps/frontend/src/app/pages/company/hiring/hiring.component.scss
  apps/frontend/src/app/pages/company/hiring/hiring.component.spec.ts
  apps/frontend/src/app/pages/company/hiring/hiring.component.ts
  apps/frontend/src/app/pages/pages-routing.module.ts
  apps/frontend/src/app/shared/components/card-job/card-job.component.html
  apps/frontend/src/app/shared/components/card-job/card-job.component.scss
  apps/frontend/src/app/shared/components/card-job/card-job.component.spec.ts
  apps/frontend/src/app/shared/components/card-job/card-job.component.ts
  apps/frontend/src/app/shared/components/input/input.component.html
  apps/frontend/src/app/shared/components/input/input.component.ts
  apps/frontend/src/app/shared/components/select/select.component.html
  apps/frontend/src/app/shared/components/select/select.component.scss
  apps/frontend/src/app/shared/components/select/select.component.spec.ts
  apps/frontend/src/app/shared/components/select/select.component.ts
  apps/frontend/src/app/shared/modal/modal.component.html
  apps/frontend/src/app/shared/modal/modal.component.ts
  apps/frontend/src/main.ts
Labels: waiting-for-review

#67 Profile and Profile update components
  apps/frontend/src/app/pages/company/profile/profile.component.html
  apps/frontend/src/app/pages/company/profile/profile.component.scss
  apps/frontend/src/app/pages/company/profile/profile.component.spec.ts
  apps/frontend/src/app/pages/company/profile/profile.component.ts
  apps/frontend/src/app/pages/pages-routing.module.ts
  apps/frontend/src/app/shared/components/input/input.component.html
  apps/frontend/src/app/shared/components/input/input.component.ts
Labels: waiting-for-review

#71 Jobs and Jobs details integration
  apps/backend/src/infra/auth/strategies/cognito-user/mocks/validate.ts
  apps/backend/src/modules/job/dto/filter-jobs.dto.ts
  apps/backend/src/modules/user/entities/create-user-response.entity.ts
  apps/backend/src/modules/user/entities/retrieve-self-response.entity.ts
  apps/backend/src/modules/user/entities/update-user-response.entity.ts
  apps/backend/src/modules/user/user.service.ts
  apps/backend/src/shared/mocks/user.ts
  apps/frontend/project.json
  apps/frontend/src/app/app.component.ts
  apps/frontend/src/app/app.config.ts
  apps/frontend/src/app/guards/auth.guard.ts
  apps/frontend/src/app/interceptors/jwt.interceptor.ts
  apps/frontend/src/app/pages/jobs-details/jobs-details.component.html
  apps/frontend/src/app/pages/jobs-details/jobs-details.component.ts
  apps/frontend/src/app/pages/jobs/jobs.component.html
  apps/frontend/src/app/pages/jobs/jobs.component.ts
  apps/frontend/src/app/services/auth/auth.service.spec.ts
  apps/frontend/src/app/services/auth/auth.service.ts
  apps/frontend/src/app/services/base-http/base-http.service.spec.ts
  apps/frontend/src/app/services/base-http/base-http.service.ts
  apps/frontend/src/app/services/job/job.service.spec.ts
  apps/frontend/src/app/services/job/job.service.ts
  apps/frontend/src/app/services/user/user.service.ts
  apps/frontend/src/app/services/wallet/wallet.service.ts
  apps/frontend/src/app/shared/components/card/card.component.html
  apps/frontend/src/app/shared/components/layout/navbar-landing/navbar-landing.component.html
  apps/frontend/src/app/shared/modal/modal.component.html
  apps/frontend/src/app/shared/utils/functions/format-enum.ts
  apps/frontend/src/environments/environment.development.ts
  apps/frontend/tsconfig.app.json
  libs/types/src/lib/user.ts
  nx.json
Labels: enhancement, release, waiting-for-review

#74 Job Applications integration
  apps/backend/src/modules/job/dto/filter-job-applications.dto.ts
  apps/backend/src/modules/job/dto/filter-user-job-applications.dto.ts
  apps/backend/src/modules/job/entities/job-applications-user-view-find-many.entity.ts
  apps/backend/src/modules/job/job.controller.ts
  apps/backend/src/modules/job/job.service.ts
  apps/frontend/src/app/pages/pages-routing.module.ts
  apps/frontend/src/app/pages/person/job-applications-all/job-applications-all.component.html
  apps/frontend/src/app/pages/person/job-applications-all/job-applications-all.component.ts
  apps/frontend/src/app/services/job/job.service.ts
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.html
  libs/types/src/lib/job.ts
Labels: enhancement, release, waiting-for-review

#72 Home Company Integrated Jobs and Hiring Page
  apps/backend/src/modules/job/dto/create-job.dto.ts
  apps/backend/src/modules/job/dto/filter-company-jobs.dto.ts
  apps/backend/src/modules/job/job.service.ts
  apps/backend/src/shared/entities/job-company-view.entity.ts
  apps/frontend/src/app/pages/company/hiring/hiring.component.html
  apps/frontend/src/app/pages/company/hiring/hiring.component.ts
  apps/frontend/src/app/pages/company/home/home.component.html
  apps/frontend/src/app/pages/company/home/home.component.ts
  apps/frontend/src/app/services/auth/auth.service.ts
  apps/frontend/src/app/services/job/job.service.ts
  apps/frontend/src/app/services/user/user.service.spec.ts
  apps/frontend/src/app/services/user/user.service.ts
  apps/frontend/src/app/shared/components/card-job/card-job.component.html
  apps/frontend/src/app/shared/components/card-job/card-job.component.ts
  apps/frontend/src/app/shared/components/select/select.component.html
  apps/frontend/src/app/shared/components/select/select.component.ts
  apps/frontend/src/app/shared/utils/functions/format-select-item.ts
  apps/frontend/src/main.ts
  libs/types/src/lib/job.ts
  prisma/schema.prisma
Labels: enhancement, release, waiting-for-review

#78 Navbar company component and navbar person adjust
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.html
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.ts
Labels: waiting-for-review

#80 Integration of List applications + see applicant profile + see results
  apps/backend/src/modules/job/dto/filter-job-applications.dto.ts
  apps/backend/src/modules/job/job.controller.ts
  apps/backend/src/modules/job/job.service.ts
  apps/frontend/src/app/pages/certificates/components/confirmation-modal/confirmation-modal.component.ts
  apps/frontend/src/app/pages/company/applications-job/applications-job.component.html
  apps/frontend/src/app/pages/company/applications-job/applications-job.component.ts
  apps/frontend/src/app/pages/company/applications-profile/applications-profile.component.html
  apps/frontend/src/app/pages/company/applications-profile/applications-profile.component.ts
  apps/frontend/src/app/pages/company/applications-results/applications-results.component.html
  apps/frontend/src/app/pages/company/applications-results/applications-results.component.ts
  apps/frontend/src/app/pages/company/hiring/hiring.component.html
  apps/frontend/src/app/pages/company/hiring/hiring.component.ts
  apps/frontend/src/app/pages/company/home/home.component.html
  apps/frontend/src/app/pages/company/home/home.component.ts
  apps/frontend/src/app/pages/pages-routing.module.ts
  apps/frontend/src/app/services/job/job.service.ts
  apps/frontend/src/app/services/user/user.service.ts
  apps/frontend/src/app/shared/components/back-button/back-button.component.ts
  apps/frontend/src/app/shared/components/card-job/card-job.component.html
  apps/frontend/src/app/shared/components/card-job/card-job.component.ts
  apps/frontend/src/app/shared/modal/modal.component.html
  libs/types/src/lib/job.ts
Labels: enhancement, release, waiting-for-review

#76 Company profile Page integration
  apps/backend/src/modules/user/dto/update-company-profile.dto.ts
  apps/backend/src/modules/user/user.controller.ts
  apps/backend/src/modules/user/user.service.ts
  apps/backend/src/shared/entities/company-profile.entity.ts
  apps/frontend/src/app/pages/company/hiring/hiring.component.ts
  apps/frontend/src/app/pages/company/profile/profile.component.html
  apps/frontend/src/app/pages/company/profile/profile.component.ts
  apps/frontend/src/app/pages/jobs-details/jobs-details.component.ts
  apps/frontend/src/app/pages/pages-routing.module.ts
  apps/frontend/src/app/services/auth/auth.service.ts
  apps/frontend/src/app/services/user/user.service.ts
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.html
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.ts
  libs/types/src/lib/company-profile.ts
  libs/types/src/lib/user.ts
  prisma/schema.prisma
Labels: enhancement, release, waiting-for-review

#81 Create Profile company (4.2, 4.2.1, 4.2.2 and 4.2.2.1)
  apps/frontend/src/app/pages/company/create-profile/create-profile.component.html
  apps/frontend/src/app/pages/company/create-profile/create-profile.component.scss
  apps/frontend/src/app/pages/company/create-profile/create-profile.component.spec.ts
  apps/frontend/src/app/pages/company/create-profile/create-profile.component.ts
  apps/frontend/src/app/pages/pages-routing.module.ts
Labels: enhancement, release, waiting-for-review

#88 fix: navbar pages menu profile
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.html
Labels: waiting-for-review

#85 Adjust navbar behavior (close when clicked away)
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.html
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.ts
Labels: waiting-for-review

#66 Add NgOptimizedImage
  apps/frontend/src/app/landing/company/company.component.html
  apps/frontend/src/app/landing/company/company.module.ts
  apps/frontend/src/app/landing/landing.module.ts
  apps/frontend/src/app/landing/student/student.component.html
  apps/frontend/src/app/landing/student/student.module.ts
  apps/frontend/src/app/pages/certificates/components/certificate/certificate.component.html
  apps/frontend/src/app/pages/certificates/components/certificate/certificate.component.ts
  apps/frontend/src/app/pages/certificates/components/confirmation-modal/confirmation-modal.component.html
  apps/frontend/src/app/pages/certificates/components/confirmation-modal/confirmation-modal.component.ts
  apps/frontend/src/app/pages/certificates/my-certificates.component.html
  apps/frontend/src/app/pages/certificates/my-certificates.component.ts
  apps/frontend/src/app/pages/company/profile/profile.component.html
  apps/frontend/src/app/pages/company/profile/profile.component.ts
  apps/frontend/src/app/pages/jobs-details/jobs-details.component.html
  apps/frontend/src/app/pages/jobs-details/jobs-details.component.ts
  apps/frontend/src/app/shared/components/card-job/card-job.component.html
  apps/frontend/src/app/shared/components/card/card.component.html
  apps/frontend/src/app/shared/components/card/card.component.ts
  apps/frontend/src/app/shared/components/files-upload/files-upload.component.html
  apps/frontend/src/app/shared/components/files-upload/files-upload.component.ts
  apps/frontend/src/app/shared/components/layout/footer/footer.component.html
  apps/frontend/src/app/shared/components/layout/footer/footer.component.ts
  apps/frontend/src/app/shared/components/layout/navbar-account/navbar-account.component.html
  apps/frontend/src/app/shared/components/layout/navbar-account/navbar-account.component.ts
  apps/frontend/src/app/shared/components/layout/navbar-landing/navbar-landing.component.html
  apps/frontend/src/app/shared/components/layout/navbar-landing/navbar-landing.component.ts
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.html
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.ts
Labels: enhancement, waiting-for-review

#83 Refactor on Pre-screening Interview page
  apps/frontend/src/app/pages/company/interview-gpt/interview-gpt.component.html
  apps/frontend/src/app/pages/company/interview-gpt/interview-gpt.component.ts
  apps/frontend/src/app/shared/components/input/input.component.html
Labels: waiting-for-review

#87 Create Profile Integration + Style Adjustments - Company
  apps/frontend/src/app/pages/company/create-profile/create-profile.component.html
  apps/frontend/src/app/pages/company/create-profile/create-profile.component.ts
  apps/frontend/src/app/pages/company/hiring/hiring.component.ts
  apps/frontend/src/app/pages/company/profile/profile.component.ts
  apps/frontend/src/app/pages/jobs-details/jobs-details.component.ts
  apps/frontend/src/app/pages/pages-routing.module.ts
  apps/frontend/src/app/services/user/user.service.ts
  yarn.lock
Labels: enhancement, release, waiting-for-review

#93 Display user/company profile image in navbar pages
  apps/frontend/src/app/pages/company/profile/profile.component.html
  apps/frontend/src/app/shared/components/card/card.component.html
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.html
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.ts
Labels: waiting-for-review

#90 fix: banner edit profile
  apps/frontend/src/app/pages/company/profile/profile.component.html
Labels: waiting-for-review

#92 Replace *ngIF and *ngFor for angular's @for and @if
  apps/frontend/src/app/pages/certificates/my-certificates.component.html
  apps/frontend/src/app/pages/certificates/my-certificates.component.ts
  apps/frontend/src/app/pages/company/interview-gpt/interview-gpt.component.ts
  apps/frontend/src/app/pages/person/gpt-list/gpt-list.component.html
  apps/frontend/src/app/pages/person/gpt-list/gpt-list.component.ts
  apps/frontend/src/app/pages/person/home/home.component.html
  apps/frontend/src/app/pages/person/home/home.component.ts
  apps/frontend/src/app/shared/components/card/card.component.html
  apps/frontend/src/app/shared/components/card/card.component.ts
  apps/frontend/src/app/shared/components/form-field/form-field.component.html
  apps/frontend/src/app/shared/components/form-field/form-field.component.ts
  apps/frontend/src/app/shared/components/input/input.component.html
  apps/frontend/src/app/shared/components/input/input.component.ts
Labels: waiting-for-review

#77 8.1.1 and 8.1.1.1 - Build training data component and new add
  apps/frontend/src/app/pages/company/build-training-data/build-training-data.component.html
  apps/frontend/src/app/pages/company/build-training-data/build-training-data.component.scss
  apps/frontend/src/app/pages/company/build-training-data/build-training-data.component.spec.ts
  apps/frontend/src/app/pages/company/build-training-data/build-training-data.component.ts
  apps/frontend/src/app/pages/pages-routing.module.ts
Labels: waiting-for-review

#98 feat: hide pages that are not ready
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.html
Labels: waiting-for-review

#102 Not found page
  apps/frontend/src/app/app.routes.ts
  apps/frontend/src/app/shared/components/not-found/not-found.component.css
  apps/frontend/src/app/shared/components/not-found/not-found.component.html
  apps/frontend/src/app/shared/components/not-found/not-found.component.spec.ts
  apps/frontend/src/app/shared/components/not-found/not-found.component.ts
Labels: enhancement, waiting-for-review

#95 Interview questions page + improvement in backend
  apps/backend/src/modules/job/dto/configure-ai-questions.dto.ts
  apps/backend/src/modules/job/job.service.ts
  apps/backend/src/shared/entities/job-application-company-view.entity.ts
  apps/frontend/src/app/pages/company/applications-profile/applications-profile.component.html
  apps/frontend/src/app/pages/company/applications-profile/applications-profile.component.ts
  apps/frontend/src/app/pages/company/hiring/hiring.component.html
  apps/frontend/src/app/pages/company/hiring/hiring.component.ts
  apps/frontend/src/app/pages/company/interview-gpt/interview-gpt.component.html
  apps/frontend/src/app/pages/company/interview-gpt/interview-gpt.component.ts
  apps/frontend/src/app/pages/pages-routing.module.ts
  apps/frontend/src/app/services/job/job.service.ts
  libs/types/src/lib/job.ts
Labels: enhancement, release
