Repository Venture-Miner/wagademy, pull requests merged in 2024-03, with the labels that each got.

#52 GPT Chat component, navbar component and modal component
  apps/frontend/src/app/app.routes.ts
  apps/frontend/src/app/pages/gpt-chat/gpt-chat.component.html
  apps/frontend/src/app/pages/gpt-chat/gpt-chat.component.scss
  apps/frontend/src/app/pages/gpt-chat/gpt-chat.component.spec.ts
  apps/frontend/src/app/pages/gpt-chat/gpt-chat.component.ts
  apps/frontend/src/app/pages/layout/navbar/navbar.component.html
  apps/frontend/src/app/pages/layout/navbar/navbar.component.scss
  apps/frontend/src/app/pages/layout/navbar/navbar.component.spec.ts
  apps/frontend/src/app/pages/layout/navbar/navbar.component.ts
  apps/frontend/src/app/pages/pages-routing.module.ts
  apps/frontend/src/app/pages/pages.component.html
  apps/frontend/src/app/pages/pages.component.ts
  apps/frontend/src/app/pages/pages.module.ts
  apps/frontend/src/app/shared/modal/modal.component.html
  apps/frontend/src/app/shared/modal/modal.component.scss
  apps/frontend/src/app/shared/modal/modal.component.spec.ts
  apps/frontend/src/app/shared/modal/modal.component.ts
  apps/frontend/src/assets/img/images/img-default-profile.svg
  apps/frontend/src/assets/img/images/img-user-profile.svg
  apps/frontend/src/main.ts
  apps/frontend/src/styles.scss
  apps/frontend/tailwind.config.js
Labels: changes-suggested, enhancement, release

#55 My certificates and "I'm buttons" animation
  apps/frontend/src/app/app.routes.ts
  apps/frontend/src/app/landing/company/company.component.html
  apps/frontend/src/app/landing/company/company.module.ts
  apps/frontend/src/app/landing/student/student.component.html
  apps/frontend/src/app/pages/certificates/components/certificate/certificate.component.css
  apps/frontend/src/app/pages/certificates/components/certificate/certificate.component.html
  apps/frontend/src/app/pages/certificates/components/certificate/certificate.component.spec.ts
  apps/frontend/src/app/pages/certificates/components/certificate/certificate.component.ts
  apps/frontend/src/app/pages/certificates/components/confirmation-modal/confirmation-modal.component.css
  apps/frontend/src/app/pages/certificates/components/confirmation-modal/confirmation-modal.component.html
  apps/frontend/src/app/pages/certificates/components/confirmation-modal/confirmation-modal.component.spec.ts
  apps/frontend/src/app/pages/certificates/components/confirmation-modal/confirmation-modal.component.ts
  apps/frontend/src/app/pages/certificates/my-certificates.component.css
  apps/frontend/src/app/pages/certificates/my-certificates.component.html
  apps/frontend/src/app/pages/certificates/my-certificates.component.spec.ts
  apps/frontend/src/app/pages/certificates/my-certificates.component.ts
  apps/frontend/src/app/pages/pages-routing.module.ts
  apps/frontend/src/app/shared/components/pagination/pagination.component.html
  apps/frontend/src/app/shared/components/pagination/pagination.component.scss
  apps/frontend/src/app/shared/components/pagination/pagination.component.spec.ts
  apps/frontend/src/app/shared/components/pagination/pagination.component.ts
  apps/frontend/src/assets/icons/icon-scroll-pointer.svg
  apps/frontend/src/assets/icons/icon-seal.svg
  apps/frontend/src/assets/icons/icon-wagademy.svg
  apps/frontend/src/assets/img/images/img-certificate-signature.svg
  apps/frontend/tailwind.config.js
Labels: enhancement, waiting-for-review

#58 User and User Profile
  .env.example
  apps/backend/src/app/app.module.ts
  apps/backend/src/infra/auth/strategies/cognito-user/mocks/validate.ts
  apps/backend/src/infra/aws/file/file.module.ts
  apps/backend/src/infra/aws/file/file.service.spec.ts
  apps/backend/src/infra/aws/file/file.service.ts
  apps/backend/src/infra/aws/file/index.ts
  apps/backend/src/infra/aws/index.ts
  apps/backend/src/infra/index.ts
  apps/backend/src/modules/user/dto/create-profile.dto.ts
  apps/backend/src/modules/user/dto/create-user-education.dto.ts
  apps/backend/src/modules/user/dto/create-user-professional-experience.dto.ts
  apps/backend/src/modules/user/dto/create-user.dto.ts
  apps/backend/src/modules/user/dto/index.ts
  apps/backend/src/modules/user/dto/update-profile.dto.ts
  apps/backend/src/modules/user/dto/update-user.dto.ts
  apps/backend/src/modules/user/entities/create-profile-response.entity.ts
  apps/backend/src/modules/user/entities/create-user-response.entity.ts
  apps/backend/src/modules/user/entities/find-profile-response.entity.ts
  apps/backend/src/modules/user/entities/index.ts
  apps/backend/src/modules/user/entities/retrieve-self-response.entity.ts
  apps/backend/src/modules/user/entities/update-profile-response.entity.ts
  apps/backend/src/modules/user/entities/update-user-response.entity.ts
  apps/backend/src/modules/user/user.controller.spec.ts
  apps/backend/src/modules/user/user.controller.ts
  apps/backend/src/modules/user/user.module.ts
  apps/backend/src/modules/user/user.service.spec.ts
  apps/backend/src/modules/user/user.service.ts
  apps/backend/src/shared/decorators/api-files.decorator.ts
  apps/backend/src/shared/decorators/index.ts
  apps/backend/src/shared/entities/index.ts
  apps/backend/src/shared/entities/profile.entity.ts
  apps/backend/src/shared/entities/user-education.entity.ts
  apps/backend/src/shared/entities/user-professional-experience.entity.ts
  apps/backend/src/shared/mocks/global.mock.ts
  apps/backend/src/shared/mocks/index.ts
  apps/backend/src/shared/mocks/user.ts
  apps/backend/tsconfig.app.json
  apps/backend/tsconfig.spec.json
  apps/frontend/tsconfig.app.json
  apps/frontend/tsconfig.spec.json
  libs/types/src/index.ts
  libs/types/src/lib/shared.ts
  libs/types/src/lib/user-profile.ts
  libs/types/src/lib/user.ts
  libs/types/tsconfig.lib.json
  package.json
  prisma/schema.prisma
  yarn.lock
Labels: enhancement, release, waiting-for-review

#51 Select profile component
  apps/frontend/src/app/account/account.component.html
  apps/frontend/src/app/account/account.component.ts
  apps/frontend/src/app/environments/environment.prod.ts
  apps/frontend/src/app/environments/environment.ts
  apps/frontend/src/app/landing/landing.component.html
  apps/frontend/src/app/landing/landing.module.ts
  apps/frontend/src/app/landing/layout/footer/footer.module.ts
  apps/frontend/src/app/landing/layout/navbar/navbar.component.spec.ts
  apps/frontend/src/app/landing/layout/navbar/navbar.component.ts
  apps/frontend/src/app/landing/layout/navbar/navbar.module.ts
  apps/frontend/src/app/pages/pages.component.html
  apps/frontend/src/app/pages/pages.component.ts
  apps/frontend/src/app/pages/pages.module.ts
  apps/frontend/src/app/services/wallet.service.ts
  apps/frontend/src/app/shared/components/layout/footer/footer.component.html
  apps/frontend/src/app/shared/components/layout/footer/footer.component.scss
  apps/frontend/src/app/shared/components/layout/footer/footer.component.spec.ts
  apps/frontend/src/app/shared/components/layout/footer/footer.component.ts
  apps/frontend/src/app/shared/components/layout/navbar-account/navbar-accont.component.spec.ts
  apps/frontend/src/app/shared/components/layout/navbar-account/navbar-account.component.html
  apps/frontend/src/app/shared/components/layout/navbar-account/navbar-account.component.scss
  apps/frontend/src/app/shared/components/layout/navbar-account/navbar-account.component.ts
  apps/frontend/src/app/shared/components/layout/navbar-landing/navbar-landing.component.html
  apps/frontend/src/app/shared/components/layout/navbar-landing/navbar-landing.component.scss
  apps/frontend/src/app/shared/components/layout/navbar-landing/navbar-landing.component.spec.ts
  apps/frontend/src/app/shared/components/layout/navbar-landing/navbar-landing.component.ts
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.html
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.scss
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.spec.ts
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.ts
  package.json
  yarn.lock
Labels: enhancement, waiting-for-review

#63 2.0.1 GPTs | Physical Person e modal (frontend)
  apps/frontend/src/app/pages/pages-routing.module.ts
  apps/frontend/src/app/pages/person/gpt-chat/gpt-chat.component.html
  apps/frontend/src/app/pages/person/gpt-chat/gpt-chat.component.scss
  apps/frontend/src/app/pages/person/gpt-chat/gpt-chat.component.spec.ts
  apps/frontend/src/app/pages/person/gpt-chat/gpt-chat.component.ts
  apps/frontend/src/app/pages/person/gpt-list/gpt-list.component.html
  apps/frontend/src/app/pages/person/gpt-list/gpt-list.component.scss
  apps/frontend/src/app/pages/person/gpt-list/gpt-list.component.spec.ts
  apps/frontend/src/app/pages/person/gpt-list/gpt-list.component.ts
  apps/frontend/src/app/shared/components/cards/cards.component.html
  apps/frontend/src/app/shared/components/cards/cards.component.ts
  apps/frontend/src/assets/img/images/img-card-VM.svg
  apps/frontend/src/assets/img/images/img-card-lens.svg
Labels: waiting-for-review

#61 2.0.2 show more jobs | Physical Person and 2.0.3 Jobs details | Physical Person
  apps/frontend/src/app/pages/certificates/components/confirmation-modal/confirmation-modal.component.html
  apps/frontend/src/app/pages/certificates/my-certificates.component.html
  apps/frontend/src/app/pages/jobs-details/jobs-details.component.html
  apps/frontend/src/app/pages/jobs-details/jobs-details.component.scss
  apps/frontend/src/app/pages/jobs-details/jobs-details.component.spec.ts
  apps/frontend/src/app/pages/jobs-details/jobs-details.component.ts
  apps/frontend/src/app/pages/jobs/jobs.component.html
  apps/frontend/src/app/pages/jobs/jobs.component.scss
  apps/frontend/src/app/pages/jobs/jobs.component.spec.ts
  apps/frontend/src/app/pages/jobs/jobs.component.ts
  apps/frontend/src/app/pages/pages-routing.module.ts
  apps/frontend/src/app/pages/person/gpt-chat/gpt-chat.component.html
  apps/frontend/src/app/shared/components/cards/cards.component.html
  apps/frontend/src/assets/img/images/img-card-content.png
  apps/frontend/src/index.html
  apps/frontend/src/styles.scss
  apps/frontend/tailwind.config.js
Labels: enhancement, waiting-for-review

#65 Applications - Person
  apps/frontend/src/app/pages/pages-routing.module.ts
  apps/frontend/src/app/pages/person/job-applications-all/job-applications-all.component.html
  apps/frontend/src/app/pages/person/job-applications-all/job-applications-all.component.scss
  apps/frontend/src/app/pages/person/job-applications-all/job-applications-all.component.spec.ts
  apps/frontend/src/app/pages/person/job-applications-all/job-applications-all.component.ts
  apps/frontend/src/app/shared/components/applications-cards/applications-cards.component.html
  apps/frontend/src/app/shared/components/applications-cards/applications-cards.component.scss
  apps/frontend/src/app/shared/components/applications-cards/applications-cards.component.spec.ts
  apps/frontend/src/app/shared/components/applications-cards/applications-cards.component.ts
Labels: waiting-for-review

#62 Job CRUD and Company Profile
  apps/backend/src/app/app.module.ts
  apps/backend/src/modules/job/dto/configure-ai-questions.dto.ts
  apps/backend/src/modules/job/dto/create-job-application.dto.ts
  apps/backend/src/modules/job/dto/create-job.dto.ts
  apps/backend/src/modules/job/dto/filter-company-jobs.dto.ts
  apps/backend/src/modules/job/dto/filter-job-applications.dto.ts
  apps/backend/src/modules/job/dto/filter-jobs.dto.ts
  apps/backend/src/modules/job/dto/filter-user-job-applications.dto.ts
  apps/backend/src/modules/job/dto/index.ts
  apps/backend/src/modules/job/dto/update-job.dto.ts
  apps/backend/src/modules/job/entities/create-job-application.entity.ts
  apps/backend/src/modules/job/entities/create-job.entity.ts
  apps/backend/src/modules/job/entities/index.ts
  apps/backend/src/modules/job/entities/invite-to-interview.entity.ts
  apps/backend/src/modules/job/entities/job-applications-company-view-find-many.entity.ts
  apps/backend/src/modules/job/entities/job-applications-user-view-find-many.entity.ts
  apps/backend/src/modules/job/entities/job-company-view-find-many.entity.ts
  apps/backend/src/modules/job/entities/job-company-view-find-one.entity.ts
  apps/backend/src/modules/job/entities/job-user-view-find-many.entity.ts
  apps/backend/src/modules/job/entities/job-user-view-find-one.entity.ts
  apps/backend/src/modules/job/entities/job-user-view-update.entity.ts
  apps/backend/src/modules/job/entities/update-job.entity.ts
  apps/backend/src/modules/job/job.controller.spec.ts
  apps/backend/src/modules/job/job.controller.ts
  apps/backend/src/modules/job/job.module.ts
  apps/backend/src/modules/job/job.service.spec.ts
  apps/backend/src/modules/job/job.service.ts
  apps/backend/src/modules/user/dto/create-company-profile.dto.ts
  apps/backend/src/modules/user/dto/create-profile.dto.ts
  apps/backend/src/modules/user/dto/create-user-education.dto.ts
  apps/backend/src/modules/user/dto/create-user-professional-experience.dto.ts
  apps/backend/src/modules/user/dto/index.ts
  apps/backend/src/modules/user/dto/update-company-profile.dto.ts
  apps/backend/src/modules/user/dto/update-user.dto.ts
  apps/backend/src/modules/user/entities/create-company-profile-response.entity.ts
  apps/backend/src/modules/user/entities/find-one-company-profile-response.entity.ts
  apps/backend/src/modules/user/entities/index.ts
  apps/backend/src/modules/user/entities/update-company-profile-response.entity.ts
  apps/backend/src/modules/user/user.controller.ts
  apps/backend/src/modules/user/user.service.ts
  apps/backend/src/shared/entities/company-profile.entity.ts
  apps/backend/src/shared/entities/index.ts
  apps/backend/src/shared/entities/job-application-company-view.entity.ts
  apps/backend/src/shared/entities/job-application-user-view.entity.ts
  apps/backend/src/shared/entities/job-company-view.entity.ts
  apps/backend/src/shared/entities/job-user-view.entity.ts
  apps/backend/src/shared/select/indext.ts
  apps/backend/src/shared/select/job-user-view.ts
  libs/types/src/index.ts
  libs/types/src/lib/company-profile.ts
  libs/types/src/lib/job.ts
  prisma/schema.prisma
Labels: enhancement, work-in-progress, release
