Repository Venture-Miner/wagademy, pull requests merged in 2024-05, with the labels that each got.

#96 fix: navbar menu pages
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.html
  apps/frontend/src/app/shared/components/layout/navbar-pages/navbar-pages.component.ts
Labels: waiting-for-review

#105 Company home page integration + Responsiveness adjustment
  apps/frontend/src/app/pages/company/home/home.component.html
  apps/frontend/src/app/pages/company/home/home.component.ts
  apps/frontend/src/app/shared/components/card-job/card-job.component.ts
  apps/frontend/src/app/shared/components/card/card.component.ts
Labels: enhancement, waiting-for-review

#103 Account type guard + remove unauthorized error while it should be forbidden
  apps/backend/src/infra/auth/guards/account-type.guard.ts
  apps/backend/src/modules/chat/chat.controller.ts
  apps/backend/src/modules/chat/chat.service.ts
  apps/backend/src/modules/job/job.controller.ts
  apps/backend/src/modules/job/job.service.ts
  apps/backend/src/modules/user/user.controller.ts
  apps/backend/src/modules/user/user.service.ts
  apps/backend/src/shared/decorators/account-type.decorator.ts
  apps/frontend/src/app/pages/person/gpt-chat/gpt-chat.component.ts
Labels: enhancement, waiting-for-review

#84 Chat bot backend and integration
  .env.example
  .gitignore
  apps/backend/src/app/app.module.ts
  apps/backend/src/main.ts
  apps/backend/src/modules/chat-bot/chat-bot.controller.spec.ts
  apps/backend/src/modules/chat-bot/chat-bot.controller.ts
  apps/backend/src/modules/chat-bot/chat-bot.module.ts
  apps/backend/src/modules/chat-bot/chat-bot.service.spec.ts
  apps/backend/src/modules/chat-bot/chat-bot.service.ts
  apps/backend/src/modules/chat-bot/dto/create-chat-bot-completion.dto.ts
  apps/backend/src/modules/chat-bot/dto/create-fine-tuning-job.dto.ts
  apps/backend/src/modules/chat-bot/dto/filter-chat-bots.dto.ts
  apps/backend/src/modules/chat-bot/dto/filter-company-chat-bots.ts
  apps/backend/src/modules/chat-bot/dto/index.ts
  apps/backend/src/modules/chat-bot/dto/invite-to-chat-bot.dto.ts
  apps/backend/src/modules/chat-bot/dto/upload-training-data.dto.ts
  apps/backend/src/modules/chat-bot/entities/chat-bot.entity.ts
  apps/backend/src/modules/chat-bot/entities/create-fine-tuning-job-response.entity.ts
  apps/backend/src/modules/chat-bot/entities/find-many-chat-bots-response.entity.ts
  apps/backend/src/modules/chat-bot/entities/find-many-training-data-response.entity.ts
  apps/backend/src/modules/chat-bot/entities/find-one-chat-bot-response.entity.ts
  apps/backend/src/modules/chat-bot/entities/get-chat-history-response.entity.ts
  apps/backend/src/modules/chat-bot/entities/index.ts
  apps/backend/src/modules/chat-bot/entities/init-chat-bot-response.entity.ts
  apps/backend/src/modules/chat-bot/entities/invite-to-chat-bot-response.entity.ts
  apps/backend/src/modules/chat-bot/entities/training-data.entity.ts
  apps/backend/src/modules/chat-bot/entities/upload-training-data-response.entity.ts
  apps/backend/src/modules/chat-bot/utils/validate-training-data.ts
  apps/backend/src/modules/chat/chat.controller.ts
  apps/backend/src/modules/chat/entities/index.ts
  apps/backend/src/modules/job/job.service.ts
  apps/backend/src/modules/user/user.service.ts
  apps/backend/src/shared/entities/chat-completion-message.entity.ts
  apps/backend/src/shared/entities/file.entity.ts
  apps/backend/src/shared/entities/index.ts
  apps/frontend/src/app/app.routes.ts
  apps/frontend/src/app/pages/company/applications-job/applications-job.component.ts
  apps/frontend/src/app/pages/company/build-training-data/build-training-data.component.html
  apps/frontend/src/app/pages/company/build-training-data/build-training-data.component.ts
  apps/frontend/src/app/pages/company/gpts/gpts.component.html
  apps/frontend/src/app/pages/company/gpts/gpts.component.ts
  apps/frontend/src/app/pages/person/gpt-chat/gpt-chat.component.ts
  apps/frontend/src/app/pages/person/gpt-list/gpt-list.component.html
  apps/frontend/src/app/pages/person/gpt-list/gpt-list.component.ts
  apps/frontend/src/app/services/chat-bot/chat-bot.service.spec.ts
  apps/frontend/src/app/services/chat-bot/chat-bot.service.ts
  apps/frontend/src/app/shared/components/select/select.component.html
  apps/frontend/src/app/shared/modal/modal.component.html
  apps/frontend/src/app/shared/modal/modal.component.ts
  apps/frontend/src/app/shared/utils/utils/obj-to-formdata.ts
  libs/types/src/index.ts
  libs/types/src/lib/chat-bot.ts
  libs/types/src/lib/shared.ts
  package.json
  prisma/schema.prisma
  yarn.lock
Labels: enhancement, release

#104 User home page integration + Responsiveness adjustment
  apps/frontend/src/app/pages/company/profile/profile.component.ts
  apps/frontend/src/app/pages/person/gpt-list/gpt-list.component.html
  apps/frontend/src/app/pages/person/gpt-list/gpt-list.component.ts
  apps/frontend/src/app/pages/person/home/home.component.html
  apps/frontend/src/app/pages/person/home/home.component.ts
  apps/frontend/src/app/shared/modal/modal.component.html
  apps/frontend/src/app/shared/modal/modal.component.ts
  libs/types/src/lib/job.ts
Labels: enhancement, waiting-for-review

#100 Create User Profile Integration
  apps/backend/src/modules/user/dto/create-profile.dto.ts
  apps/backend/src/modules/user/dto/create-user-education.dto.ts
  apps/backend/src/modules/user/dto/create-user-professional-experience.dto.ts
  apps/frontend/src/app/pages/pages-routing.module.ts
  apps/frontend/src/app/pages/person/user-profile/components/education/education.component.html
  apps/frontend/src/app/pages/person/user-profile/components/education/education.component.ts
  apps/frontend/src/app/pages/person/user-profile/components/expertise/expertise.component.html
  apps/frontend/src/app/pages/person/user-profile/components/expertise/expertise.component.ts
  apps/frontend/src/app/pages/person/user-profile/components/photo-upload/photo-upload.component.html
  apps/frontend/src/app/pages/person/user-profile/components/professional-experience/professional-experience.component.html
  apps/frontend/src/app/pages/person/user-profile/components/professional-experience/professional-experience.component.ts
  apps/frontend/src/app/pages/person/user-profile/components/skills/skills.component.html
  apps/frontend/src/app/pages/person/user-profile/components/skills/skills.component.ts
  apps/frontend/src/app/pages/person/user-profile/components/user-data/user-data.component.html
  apps/frontend/src/app/pages/person/user-profile/components/user-data/user-data.component.ts
  apps/frontend/src/app/pages/person/user-profile/user-profile.component.html
  apps/frontend/src/app/pages/person/user-profile/user-profile.component.ts
  apps/frontend/src/app/services/user/user.service.ts
Labels: enhancement, release

#50 Payment release
  apps/backend/src/app/app.module.ts
  apps/backend/src/infra/auth/strategies/cognito-user/mocks/validate.ts
  apps/backend/src/modules/payment/dto/buy-credits.dto.ts
  apps/backend/src/modules/payment/dto/create-subscription.dto.ts
  apps/backend/src/modules/payment/dto/customer-portal.dto.ts
  apps/backend/src/modules/payment/dto/index.ts
  apps/backend/src/modules/payment/dto/update-subscription.dto.ts
  apps/backend/src/modules/payment/entities/checkout-response.entity.ts
  apps/backend/src/modules/payment/entities/credits.entity.ts
  apps/backend/src/modules/payment/entities/find-many-plans.entity.ts
  apps/backend/src/modules/payment/entities/get-stripe-customer-portal.entity.ts
  apps/backend/src/modules/payment/entities/get-user-current-credits.entity.ts
  apps/backend/src/modules/payment/entities/index.ts
  apps/backend/src/modules/payment/mock/payment.ts
  apps/backend/src/modules/payment/payment.controller.spec.ts
  apps/backend/src/modules/payment/payment.controller.ts
  apps/backend/src/modules/payment/payment.module.ts
  apps/backend/src/modules/payment/payment.service.spec.ts
  apps/backend/src/modules/payment/payment.service.ts
  apps/backend/src/modules/stripe/mock/stripe.ts
  apps/backend/src/modules/stripe/stripe-config.module.ts
  apps/backend/src/modules/stripe/stripe-webhook.service.spec.ts
  apps/backend/src/modules/stripe/stripe-webhook.service.ts
  apps/backend/src/modules/stripe/stripe.controller.spec.ts
  apps/backend/src/modules/stripe/stripe.controller.ts
  apps/backend/src/modules/stripe/stripe.module.ts
  apps/backend/src/modules/user/entities/create-user-response.entity.ts
  apps/backend/src/modules/user/entities/retrieve-self-response.entity.ts
  apps/backend/src/modules/user/entities/update-user-response.entity.ts
  apps/backend/src/modules/user/user.service.ts
  apps/backend/src/services/stripe/mock/stripe.ts
  apps/backend/src/services/stripe/stripe.service.spec.ts
  apps/backend/src/services/stripe/stripe.service.ts
  apps/backend/src/shared/entities/index.ts
  apps/backend/src/shared/entities/plan.entity.ts
  apps/backend/src/shared/mocks/index.ts
  apps/backend/src/shared/mocks/plan.ts
  apps/backend/src/shared/mocks/user.ts
  libs/types/src/index.ts
  libs/types/src/lib/credit.ts
  libs/types/src/lib/payment.ts
  libs/types/src/lib/plan.ts
  libs/types/src/lib/user.ts
  package.json
  prisma/schema.prisma
  scripts/seed/seed.ts
  scripts/seed/seeds/plan.ts
  yarn.lock
Labels: enhancement, release, waiting-for-review

#108 View and edit profile integration
  apps/backend/src/modules/user/entities/retrieve-self-response.entity.ts
  apps/backend/src/modules/user/user.service.ts
  apps/frontend/src/app/pages/person/user-profile/components/education/education.component.html
  apps/frontend/src/app/pages/person/user-profile/components/expertise/expertise.component.html
  apps/frontend/src/app/pages/person/user-profile/components/expertise/expertise.component.ts
  apps/frontend/src/app/pages/person/user-profile/components/photo-upload/photo-upload.component.html
  apps/frontend/src/app/pages/person/user-profile/components/photo-upload/photo-upload.component.ts
  apps/frontend/src/app/pages/person/user-profile/components/skills/skills.component.html
  apps/frontend/src/app/pages/person/user-profile/components/skills/skills.component.ts
  apps/frontend/src/app/pages/person/user-profile/components/user-data/user-data.component.html
  apps/frontend/src/app/pages/person/user-profile/components/user-data/user-data.component.ts
  apps/frontend/src/app/pages/person/user-profile/user-profile.component.html
  apps/frontend/src/app/pages/person/user-profile/user-profile.component.ts
  apps/frontend/src/app/services/user/user.service.ts
  apps/frontend/src/app/shared/components/user-profile-display/user-profile-display.component.css
  apps/frontend/src/app/shared/components/user-profile-display/user-profile-display.component.html
  apps/frontend/src/app/shared/components/user-profile-display/user-profile-display.component.spec.ts
  apps/frontend/src/app/shared/components/user-profile-display/user-profile-display.component.ts
  libs/types/src/lib/user.ts
  yarn.lock
Labels: changes-suggested, enhancement, release

#99 Loading component
  apps/frontend/src/app/pages/company/applications-job/applications-job.component.html
  apps/frontend/src/app/pages/company/applications-job/applications-job.component.ts
  apps/frontend/src/app/pages/company/applications-profile/applications-profile.component.html
  apps/frontend/src/app/pages/company/applications-profile/applications-profile.component.ts
  apps/frontend/src/app/pages/company/applications-results/applications-results.component.html
  apps/frontend/src/app/pages/company/applications-results/applications-results.component.ts
  apps/frontend/src/app/pages/company/build-training-data/build-training-data.component.html
  apps/frontend/src/app/pages/company/build-training-data/build-training-data.component.ts
  apps/frontend/src/app/pages/company/gpts/gpts.component.html
  apps/frontend/src/app/pages/company/gpts/gpts.component.ts
  apps/frontend/src/app/pages/company/hiring/hiring.component.html
  apps/frontend/src/app/pages/company/hiring/hiring.component.ts
  apps/frontend/src/app/pages/company/home/home.component.html
  apps/frontend/src/app/pages/company/home/home.component.ts
  apps/frontend/src/app/pages/company/profile/profile.component.html
  apps/frontend/src/app/pages/company/profile/profile.component.ts
  apps/frontend/src/app/pages/jobs-details/jobs-details.component.html
  apps/frontend/src/app/pages/jobs-details/jobs-details.component.ts
  apps/frontend/src/app/pages/jobs/jobs.component.html
  apps/frontend/src/app/pages/jobs/jobs.component.ts
  apps/frontend/src/app/pages/person/gpt-list/gpt-list.component.html
  apps/frontend/src/app/pages/person/gpt-list/gpt-list.component.ts
  apps/frontend/src/app/pages/person/home/home.component.html
  apps/frontend/src/app/pages/person/home/home.component.ts
  apps/frontend/src/app/pages/person/job-applications-all/job-applications-all.component.html
  apps/frontend/src/app/pages/person/job-applications-all/job-applications-all.component.ts
  apps/frontend/src/app/shared/components/loading/loading.component.html
  apps/frontend/src/app/shared/components/loading/loading.component.scss
  apps/frontend/src/app/shared/components/loading/loading.component.spec.ts
  apps/frontend/src/app/shared/components/loading/loading.component.ts
Labels: waiting-for-review
